# Generated by Django 4.2.16 on 2024-10-26 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ccontact',
            new_name='Contact',
        ),
    ]
